
build:
  version: "2.0"

accounts:
  message: "Welcome to ZettaBank accounts related QA APIs "
  contactDetails:
    name: "Sanjay - QA Lead"
    email: "sanjay@zettabank.com"
  onCallSupport:
    - (040) 265-3765
    - (040) 734-8371

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/accountsdb
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root
 
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
