
build:
  version: "1.0"

accounts:
  message: "Welcome to ZettaBank loans related prod APIs "
  contactDetails:
    name: "Rafi - Product Owner"
    email: "rafi@zettabank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

spring:
 management:
  endpoints:
    web:
      exposure:
        include:
        - "*"