
build:
  version: "1.829"

loans:
  message: "Welcome to ZettaBank loans related qa  APIs "
  contactDetails:
    name: "sai kumar - Product Owner"
    email: "sai1919@zettabank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

spring:
 management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
